export const LOAD = 'LOAD';
export const SET_SHIPPING_DATA = 'SET_SHIPPING_DATA';
export const SET_PAYMENT_DATA = 'SET_PAYMENT_DATA';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';
export const UNSET_ORDERED_STATE = 'UNSET_ORDERED_STATE';