export const LOAD = "LOAD";
export const STORE_CURRENT_PRODUCT = 'STORE_CURRENT_PRODUCT';
export const RENDER_CART_PRODUCTS = "RENDER_CART_PRODUCTS";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_PRODUCT_QUANTITY = "UPDATE_PRODUCT_QUANTITY";

export const SET_ORDERING_STATE = 'SET_ORDERING_STATE';
export const UNSET_ORDERING_STATE = 'UNSET_ORDERING_STATE';