export const LOAD = 'LOAD';
export const RENDER_ORDERS = 'RENDER_ORDERS';

export const RENDER_USERS = 'RENDER_USERS';
export const RENDER_USER_DETAILS = 'RENDER_USER_DETAILS';
export const CONSIDER_DELETED_USER = 'CONSIDER_DELETED_USER';
export const EMPTY_USER_DETAILS = 'EMPTY_USER_DETAILS';
export const UNSET_USER_EDITED_STATE = 'UNSET_USER_EDITED_STATE';
export const UNSET_USER_DELETED_STATE = 'UNSET_USER_DELETED_STATE';

export const RENDER_PRODUCTS = 'RENDER_PRODUCTS';
export const RENDER_ADMIN_PRODUCT_DETAILS = 'RENDER_ADMIN_PRODUCT_DETAILS';
export const SET_PRODUCT_EDITED_STATE = 'SET_PRODUCT_EDITED_STATE';
export const UNSET_PRODUCT_EDITED_STATE = 'UNSET_PRODUCT_EDITED_STATE';
export const CONSIDER_DELETED_PRODUCT = 'CONSIDER_DELETED_PRODUCT';
export const SET_PRODUCT_ADDED_STATE = 'SET_PRODUCT_ADDED_STATE';
export const UNSET_PRODUCT_ADDED_STATE = 'UNSET_PRODUCT_ADDED_STATE';
